[package]
name = "wrenlet-sys"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
bindgen = "0.71.1"
cc = "1.0"

[features]
default = ["meta", "random", "wren_v0_4_0"]
meta = []
random = []

wren_v0_4_0 = []
